version: '3.5'
services:
  tjmt-node:
    image: tjmt/angular:node-${NODE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        SONAR_SCANNER_NPM_VERSION: ${SONAR_SCANNER_NPM_VERSION}
        SONAR_SCANNER_CLI_VERSION: ${SONAR_SCANNER_CLI_VERSION}